apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: sfo-enterprise-contract
  namespace: sfo-security-tenant
spec:
  params: 
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/app-interface-standard
  application: splunk-forwarder-operator
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git